export const ACCOUNT_BALANCE_FETCHED = 'ACCOUNT_BALANCE_FETCHED'
export const ACCOUNT_BALANCES_FETCHED = 'ACCOUNT_BALANCES_FETCHED'
export const ACCOUNT_BALANCES_FETCHING = 'ACCOUNT_BALANCES_FETCHING'
export const ACCOUNT_BALANCES_FAILED = 'ACCOUNT_BALANCES_FAILED'

export function accountBalancesFetching (web3) {
  return {
    type: ACCOUNT_BALANCES_FETCHING,
    web3
  }
}
